In [1]:
import cv2
import numpy as np

In [2]:
img1 = cv2.imread("a.png")
print(img1)
print(img1.shape)

[[[255 255 255]
  [255 255 255]
  [248 248 253]
  ...
  [238 238 238]
  [238 238 238]
  [238 238 238]]

 [[217 162 143]
  [202 129  96]
  [202 108  65]
  ...
  [238 238 238]
  [238 238 238]
  [238 238 238]]

 [[215  96  40]
  [215  96  40]
  [214 126  76]
  ...
  [238 238 238]
  [238 238 238]
  [238 238 238]]

 ...

 [[238 238 238]
  [238 238 238]
  [238 238 238]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[238 238 238]
  [238 238 238]
  [238 238 238]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[238 238 238]
  [238 238 238]
  [238 238 238]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
(326, 360, 3)


In [3]:
Rimg1 = cv2.resize(img1, (300,300))
cv2.imshow("aya", Rimg1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
directory = r"D:\New folder"
file_name = 'saved image.png'
cv2.imwrite(file_name,Rimg1)

True

In [5]:
vid = cv2.VideoCapture(0)
fourcc = cv2.VideoWriter_fourcc(*'XVID')
out = cv2.VideoWriter('output.avi', fourcc , 20.0 , (640,480))

print(vid.isOpened())
while(vid.isOpened):
    ret , Frame =vid.read()
    
    out.write(Frame)
    
    cv2.imshow("aya", Frame)
    
    if cv2.waitKey(1) == ord('q'):
         break
vid.release()        
out.release()    
cv2.destroyAllWindows()

True
